import "./fonts";

export const proseClasses = [
  "prose prose-sm sm:prose-base lg:prose-lg",
  "prose-img:rounded-xl prose-img:m-0",

  "prose-headings:text-foreground prose-headings:m-0",

  "prose-h1:[color:var(--title-color)]",
  "prose-h1:[margin-top:var(--margin-h1)] prose-h1:[margin-bottom:var(--margin-h1)]",
  "prose-h1:text-6xl",
  "prose-h1:[text-align:var(--title-align)]",
  "prose-h1:font-[family-name:var(--title-font)]",
  "prose-h1:font-[var(--title-weight)]",
  "prose-h1:[font-style:var(--title-style)]",
  "prose-h1:[font-size:var(--title-size)]",
  "prose-h1:[line-height:var(--title-line-height)]",
  "prose-h1:[letter-spacing:var(--title-letter-spacing)]",
  "prose-h2:[color:var(--subtitle-color)]",
  "prose-h2:[margin-top:var(--margin-h2)] prose-h2:[margin-bottom:var(--margin-h2)]",
  "prose-h2:[text-align:var(--title-align)]",
  "prose-h2:font-[family-name:var(--subtitle-font)]",
  "prose-h2:font-[var(--subtitle-weight)]",
  "prose-h2:[font-style:var(--subtitle-style)]",
  "prose-h2:[font-size:var(--subtitle-size)]",
  "prose-h2:[color:var(--subtitle-color)]",
  "prose-h2:[line-height:var(--subtitle-line-height)]",
  "prose-h2:[letter-spacing:var(--subtitle-letter-spacing)]",
  "prose-h3:[color:var(--header-color)]",
  "prose-h3:[margin-top:var(--margin-h3)] prose-h3:[margin-bottom:var(--margin-h3)]",
  "prose-h3:font-[family-name:var(--header-font)]",
  "prose-h3:font-[var(--header-weight)]",
  "prose-h3:[font-style:var(--header-style)]",
  "prose-h3:[font-size:var(--header-size)]",
  "prose-h3:[line-height:var(--header-line-height)]",
  "prose-h3:[letter-spacing:var(--header-letter-spacing)]",
  "prose-p:[margin-top:var(--margin-paragraph)] prose-p:[margin-bottom:var(--margin-paragraph)]",
  "prose-p:font-[family-name:var(--paragraph-font)]",
  "prose-p:font-[var(--paragraph-weight)]",
  "prose-p:[font-style:var(--paragraph-style)]",
  "prose-p:[font-size:var(--paragraph-size)]",
  "prose-p:[line-height:var(--paragraph-line-height)]",
  "prose-p:[letter-spacing:var(--paragraph-letter-spacing)]",
  "prose-p:[color:var(--paragraph-color)]",
  "prose-h2:[letter-spacing:var(--subtitle-letter-spacing)]",

  "prose-ul:[margin-top:var(--margin-list)] prose-ul:[margin-bottom:var(--margin-list)]",
  "prose-ol:[margin-top:var(--margin-list)] prose-ol:[margin-bottom:var(--margin-list)]",
  "focus:outline-none",
].join(" ");
