import "./fonts";

export const proseClasses = [
  "prose prose-sm sm:prose-base lg:prose-lg",

  "prose-img:[radius:var(--image-border-radius)]",
  "prose-img:m-0",
  "prose-h1:[color:var(--title-color)]",
  "prose-h1:[margin-top:var(--header-margin)] prose-h1:[margin-bottom:var(--header-margin)]",
  "prose-h1:text-6xl",
  "prose-h1:[text-align:var(--title-align)]",
  "prose-h1:font-[family-name:var(--title-font)]",
  "prose-h1:font-[var(--title-weight)]",
  "prose-h1:[font-style:var(--title-style)]",
  "prose-h1:[font-size:var(--title-size)]",
  "prose-h1:[line-height:var(--title-line-height)]",
  "prose-h1:[letter-spacing:var(--title-letter-spacing)]",

  "prose-h2:[color:var(--subtitle-color)]",
  "prose-h2:[margin-top:var(--header-margin)] prose-h2:[margin-bottom:var(--header-margin)]",
  "prose-h2:[text-align:var(--title-align)]",
  "prose-h2:font-[family-name:var(--subtitle-font)]",
  "prose-h2:font-[var(--subtitle-weight)]",
  "prose-h2:[font-style:var(--subtitle-style)]",
  "prose-h2:[font-size:var(--subtitle-size)]",
  "prose-h2:[line-height:var(--subtitle-line-height)]",
  "prose-h2:[letter-spacing:var(--subtitle-letter-spacing)]",

  "prose-h3:[color:var(--header-color)]",
  "prose-h3:[margin-top:var(--header-margin)] prose-h3:[margin-bottom:var(--header-margin)]",
  "prose-h3:font-[family-name:var(--header-font)]",
  "prose-h3:font-[var(--header-weight)]",
  "prose-h3:[font-style:var(--header-style)]",
  "prose-h3:[font-size:var(--header-size)]",
  "prose-h3:[line-height:var(--header-line-height)]",
  "prose-h3:[letter-spacing:var(--header-letter-spacing)]",

  "prose-h4:[color:var(--header-color)]",
  "prose-h4:[margin-top:var(--header-margin)] prose-h4:[margin-bottom:var(--header-margin)]",
  "prose-h4:font-[family-name:var(--header-font)]",
  "prose-h4:font-[var(--header-weight)]",
  "prose-h4:[font-style:var(--header-style)]",
  "prose-h4:[font-size:1.3rem]",
  "prose-h4:[line-height:var(--header-line-height)]",
  "prose-h4:[letter-spacing:var(--header-letter-spacing)]",

  "prose-p:[margin-top:var(--paragraph-margin)] prose-p:[margin-bottom:var(--paragraph-margin)]",
  "prose-p:font-[family-name:var(--paragraph-font)]",
  "prose-p:font-[var(--paragraph-weight)]",
  "prose-p:[font-style:var(--paragraph-style)]",
  "prose-p:[font-size:var(--paragraph-size)]",
  "prose-p:[line-height:var(--paragraph-line-height)]",
  "prose-p:[letter-spacing:var(--paragraph-letter-spacing)]",
  "prose-p:[color:var(--paragraph-color)]",

  "prose-ul:font-[family-name:var(--list-font)]",
  "prose-ul:font-[var(--list-weight)]",
  "prose-ul:[font-style:var(--list-style)]",
  "prose-ul:[font-size:var(--list-size)]",
  "prose-ul:[line-height:var(--list-line-height)]",
  "prose-ul:[letter-spacing:var(--list-letter-spacing)]",
  "prose-ul:[color:var(--list-color)]",
  "prose-ul:[margin-top:var(--list-margin-top)]",
  "prose-ul:[margin-bottom:var(--list-margin-bottom)]",

  "prose-ol:font-[family-name:var(--list-font)]",
  "prose-ol:font-[var(--list-weight)]",
  "prose-ol:[font-style:var(--list-style)]",
  "prose-ol:[font-size:var(--list-size)]",
  "prose-ol:[line-height:var(--list-line-height)]",
  "prose-ol:[letter-spacing:var(--list-letter-spacing)]",
  "prose-ol:[color:var(--list-color)]",
  "prose-ol:[margin-top:var(--list-margin-top)]",
  "prose-ol:[margin-bottom:var(--list-margin-bottom)]",

  "prose-li:font-[family-name:var(--list-font)]",
  "prose-li:font-[var(--list-weight)]",
  "prose-li:[font-style:var(--list-style)]",
  "prose-li:[font-size:var(--list-size)]",
  "prose-li:[line-height:var(--list-line-height)]",
  "prose-li:[letter-spacing:var(--list-letter-spacing)]",
  "prose-li:[color:var(--list-color)]",

  "prose-ul:[--tw-prose-bullets:var(--list-color)]",
  "prose-ol:[--tw-prose-bullets:var(--list-color)]",
  "prose-ul:[--tw-prose-counters:var(--list-color)]",
  "prose-ol:[--tw-prose-counters:var(--list-color)]",

  "prose-strong:font-[var(--strong-weight)]",

  "focus:outline-none",
].join(" ");
