export const walletConnectTheme = {
  "--ck-font-family": "Inter, var(--font-geist-sans), sans-serif",
  "--ck-font-weight": "400",
  "--ck-border-radius": "calc(var(--radius) + 4px)",
  "--ck-overlay-backdrop-filter": "blur(0px)",
  "--ck-modal-heading-font-weight": "600",
  "--ck-qr-border-radius": "var(--radius)",
  "--ck-connectbutton-font-size": "14px",
  "--ck-connectbutton-color": "hsl(var(--foreground))",
  "--ck-connectbutton-background": "hsl(var(--secondary))",
  "--ck-connectbutton-background-secondary": "hsl(var(--card))",
  "--ck-connectbutton-border-radius": "var(--radius)",
  "--ck-connectbutton-box-shadow": "none",
  "--ck-connectbutton-hover-color": "hsl(var(--foreground))",
  "--ck-connectbutton-hover-background": "hsl(var(--accent))",
  "--ck-connectbutton-hover-box-shadow": "none",
  "--ck-connectbutton-active-color": "hsl(var(--foreground))",
  "--ck-connectbutton-active-background": "hsl(var(--muted))",
  "--ck-connectbutton-active-box-shadow": "none",
  "--ck-connectbutton-balance-color": "hsl(var(--foreground))",
  "--ck-connectbutton-balance-background": "hsl(var(--card))",
  "--ck-connectbutton-balance-box-shadow": "inset 0 0 0 1px hsl(var(--border))",
  "--ck-connectbutton-balance-hover-background": "hsl(var(--secondary))",
  "--ck-connectbutton-balance-hover-box-shadow": "inset 0 0 0 1px hsl(var(--accent))",
  "--ck-connectbutton-balance-active-background": "hsl(var(--muted))",
  "--ck-connectbutton-balance-active-box-shadow": "inset 0 0 0 1px hsl(var(--muted))",
  "--ck-primary-button-font-weight": "600",
  "--ck-primary-button-border-radius": "var(--radius)",
  "--ck-primary-button-color": "hsl(var(--secondary-foreground))",
  "--ck-primary-button-background": "hsl(var(--secondary))",
  "--ck-primary-button-box-shadow": "none",
  "--ck-primary-button-hover-color": "hsl(var(--secondary-foreground))",
  "--ck-primary-button-hover-background": "hsl(var(--primary) / 0.9)",
  "--ck-primary-button-hover-box-shadow": "none",
  "--ck-primary-button-active-color": "hsl(var(--secondary-foreground))",
  "--ck-primary-button-active-background": "hsl(var(--secondary) / 0.8)",
  "--ck-primary-button-active-box-shadow": "none",
  "--ck-secondary-button-font-weight": "500",
  "--ck-secondary-button-border-radius": "var(--radius)",
  "--ck-secondary-button-color": "hsl(var(--secondary-foreground))",
  "--ck-secondary-button-background": "hsl(var(--secondary))",
  "--ck-secondary-button-box-shadow": "none",
  "--ck-secondary-button-hover-color": "hsl(var(--accent-foreground))",
  "--ck-secondary-button-hover-background": "hsl(var(--accent))",
  "--ck-secondary-button-hover-box-shadow": "none",
  "--ck-secondary-button-active-color": "hsl(var(--accent-foreground))",
  "--ck-secondary-button-active-background": "hsl(var(--muted))",
  "--ck-secondary-button-active-box-shadow": "none",
  "--ck-tertiary-button-font-weight": "500",
  "--ck-tertiary-button-border-radius": "var(--radius)",
  "--ck-tertiary-button-color": "hsl(var(--muted-foreground))",
  "--ck-tertiary-button-background": "transparent",
  "--ck-tertiary-button-box-shadow": "none",
  "--ck-tertiary-button-hover-color": "hsl(var(--foreground))",
  "--ck-tertiary-button-hover-background": "hsl(var(--accent))",
  "--ck-tertiary-button-hover-box-shadow": "none",
  "--ck-tertiary-button-active-color": "hsl(var(--foreground))",
  "--ck-tertiary-button-active-background": "hsl(var(--muted))",
  "--ck-tertiary-button-active-box-shadow": "none",
  "--ck-modal-box-shadow": "0 4px 12px hsla(var(--foreground), 0.1)",
  "--ck-overlay-background": "hsla(var(--background), 0.8)",
  "--ck-body-color": "hsl(var(--foreground))",
  "--ck-body-color-muted": "hsl(var(--muted-foreground))",
  "--ck-body-color-muted-hover": "hsl(var(--foreground))",
  "--ck-body-background": "hsl(var(--background))",
  "--ck-body-background-transparent": "transparent",
  "--ck-body-background-secondary": "hsl(var(--secondary))",
  "--ck-body-background-secondary-hover-background": "hsl(var(--accent))",
  "--ck-body-background-secondary-hover-outline": "hsl(var(--ring))",
  "--ck-body-background-tertiary": "hsl(var(--muted))",
  "--ck-body-action-color": "hsl(var(--muted-foreground))",
  "--ck-body-divider": "hsl(var(--border))",
  "--ck-body-color-danger": "hsl(var(--destructive))",
  "--ck-body-color-valid": "hsl(142.1 76.2% 36.3%)",
  "--ck-siwe-border": "hsl(var(--border))",
  "--ck-body-disclaimer-background": "hsl(var(--muted))",
  "--ck-body-disclaimer-color": "hsl(var(--muted-foreground))",
  "--ck-body-disclaimer-link-color": "hsl(var(--primary))",
  "--ck-body-disclaimer-link-hover-color": "hsl(var(--foreground))",
  "--ck-tooltip-background": "hsl(var(--popover))",
  "--ck-tooltip-background-secondary": "hsl(var(--secondary))",
  "--ck-tooltip-color": "hsl(var(--popover-foreground))",
  "--ck-tooltip-shadow": "0 2px 8px hsla(var(--foreground), 0.1)",
  "--ck-dropdown-button-color": "hsl(var(--muted-foreground))",
  "--ck-dropdown-button-box-shadow": "0 0 0 1px hsl(var(--border))",
  "--ck-dropdown-button-background": "hsl(var(--card))",
  "--ck-dropdown-button-hover-color": "hsl(var(--foreground))",
  "--ck-dropdown-button-hover-background": "hsl(var(--secondary))",
  "--ck-qr-dot-color": "hsl(var(--foreground))",
  "--ck-qr-background": "hsl(var(--background))",
  "--ck-qr-border-color": "hsl(var(--border))",
  "--ck-focus-color": "hsl(var(--ring))",
  "--ck-spinner-color": "hsl(var(--primary))",
  "--ck-copytoclipboard-stroke": "hsl(var(--muted-foreground))",
  "--ck-recent-badge-color": "hsl(var(--secondary-foreground))",
  "--ck-recent-badge-background": "hsl(var(--secondary))",
  "--ck-recent-badge-border-radius": "var(--radius)",
};
